name: Mobile-iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build-iOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with: { haxe-version: 4.3.6 }

      - name: Install libs
        run: |
          haxelib install hxcpp
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install polymod
          haxelib install hscript
          haxelib install json2object
          haxelib install flxanimate
          haxelib git polymod https://github.com/T5mpler/polymod-dnb

      - name: Fix hxcpp config
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?><xml><section id="vars"><set name="HXCPP_CPP11" value="1"/><set name="HXCPP_NO_PCH" value="1"/><set name="HXCPP_NO_NIL" value="1"/><set name="HXCPP_CLANG" value="1"/></section></xml>' > ~/.hxcpp_config.xml

      - name: Build iOS
        run: haxelib run lime build ios -nosign -D officialBuild

      - name: Package IPA
        run: |
          cd export/release/ios/build/*-iphoneos
          mkdir Payload
          mv *.app Payload/
          zip -r ~/VsDnB.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ~/VsDnB.ipa
